- link: https://media.damidoop.xyz
  name: Jellyfin
  desc: My self-hosted streaming service! Closed for the public.
- link: https://cloud.damidoop.xyz
  name: Nextcloud
  desc: Self-hosted alternative to O365 or G-Suite!